platform :ios, '7.0'

target :ZhiHuDaily do
  pod 'Mantle', '~>1.5'
  pod 'Masonry'
  pod 'SDWebImage', '~>3.7'
  pod 'ReactiveCocoa'
  pod 'AFNetworking'
  pod 'ECSlidingViewController', '~>2.0.3'
end
